// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(unfydqryFFI)
import unfydqryFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_unfydqry_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_unfydqry_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A persistent full-text search index backed by SQLite.
 *
 * Create one with `SearchEngine(dbPath:)` for the default behaviour, or
 * `SearchEngine.withConfig(dbPath:config:)` to choose a normalization profile
 * and a search strategy. Add or update documents with `index`, drop them with
 * `remove`, and query with `search`. The instance is safe to share across
 * threads.
 *
 * The engine stores both the raw host text and its normalized form, so the
 * index can be regenerated in place after a normalization change — explicitly
 * via `reindex`, or automatically by opening with
 * `SearchEngine.withConfigRebuilding(dbPath:config:)`.
 */
public protocol SearchEngineProtocol : AnyObject {
    
    /**
     * Adds, or replaces, the document stored under `id`.
     *
     * The host passes raw `text`; normalization runs inside the engine, so the
     * engine's profile is applied identically to indexed text and to queries.
     * Calling `index` again with an existing `id` overwrites that document.
     */
    func index(id: Int64, text: String) throws 
    
    /**
     * Regenerates the index by re-normalizing every stored document's raw text
     * with this engine's current profile, then stamps that profile.
     *
     * Use this after changing the normalization profile (or its underlying
     * rules) to bring already-indexed documents back in sync without the host
     * re-feeding them. Documents indexed before raw text was retained have no
     * raw to normalize and are skipped. Returns the number of documents
     * regenerated.
     */
    func reindex() throws  -> UInt64
    
    /**
     * Removes the document stored under `id`. A no-op if no such document
     * exists.
     */
    func remove(id: Int64) throws 
    
    /**
     * Searches the index and returns at most `limit` hits.
     *
     * The `query` is normalized with the engine's profile and then matched
     * using the engine's strategy. A query that is empty — or only whitespace
     * once normalized — returns no hits. Ordering and scoring depend on the
     * strategy (see `Hit.score`).
     */
    func search(query: String, limit: UInt32) throws  -> [Hit]
    
}

/**
 * A persistent full-text search index backed by SQLite.
 *
 * Create one with `SearchEngine(dbPath:)` for the default behaviour, or
 * `SearchEngine.withConfig(dbPath:config:)` to choose a normalization profile
 * and a search strategy. Add or update documents with `index`, drop them with
 * `remove`, and query with `search`. The instance is safe to share across
 * threads.
 *
 * The engine stores both the raw host text and its normalized form, so the
 * index can be regenerated in place after a normalization change — explicitly
 * via `reindex`, or automatically by opening with
 * `SearchEngine.withConfigRebuilding(dbPath:config:)`.
 */
open class SearchEngine:
    SearchEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_unfydqry_fn_clone_searchengine(self.pointer, $0) }
    }
    /**
     * Opens the index with the default behaviour (loose normalization +
     * trigram/bm25). Kept for backward compatibility.
     */
public convenience init(dbPath: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_constructor_searchengine_new(
        FfiConverterString.lower(dbPath),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_unfydqry_fn_free_searchengine(pointer, $0) }
    }

    
    /**
     * Opens the index with a host-selected combination of normalization
     * profile and search strategy.
     *
     * If the index already holds documents normalized under a *different*
     * profile, this returns `ConfigMismatch` rather than silently mixing
     * profiles. To regenerate the index under the new profile instead of
     * failing, open with `withConfigRebuilding`, or call `reindex` on an
     * engine opened with the matching profile.
     */
public static func withConfig(dbPath: String, config: EngineConfig)throws  -> SearchEngine {
    return try  FfiConverterTypeSearchEngine.lift(try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withconfig(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineConfig.lower(config),$0
    )
})
}
    
    /**
     * Opens the index under `config`, regenerating it in place when the stored
     * documents were normalized under a different profile.
     *
     * Unlike `withConfig`, a profile change is not an error here: the engine
     * re-normalizes every stored document from its retained raw text under the
     * new profile before returning. Documents indexed before raw text was
     * retained cannot be regenerated and are left untouched.
     */
public static func withConfigRebuilding(dbPath: String, config: EngineConfig)throws  -> SearchEngine {
    return try  FfiConverterTypeSearchEngine.lift(try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withconfigrebuilding(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineConfig.lower(config),$0
    )
})
}
    
    /**
     * Like `withConfig`, but selects normalization with a composable
     * `NormalizeOptions` set instead of a named preset. A fingerprint mismatch
     * with the stored index is a `ConfigMismatch`; use `withOptionsRebuilding`
     * to regenerate instead.
     */
public static func withOptions(dbPath: String, config: EngineOptionsConfig)throws  -> SearchEngine {
    return try  FfiConverterTypeSearchEngine.lift(try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withoptions(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineOptionsConfig.lower(config),$0
    )
})
}
    
    /**
     * Like `withConfigRebuilding`, but selects normalization with a composable
     * `NormalizeOptions` set. A change in the enabled steps regenerates the
     * index in place from the retained raw text.
     */
public static func withOptionsRebuilding(dbPath: String, config: EngineOptionsConfig)throws  -> SearchEngine {
    return try  FfiConverterTypeSearchEngine.lift(try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withoptionsrebuilding(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineOptionsConfig.lower(config),$0
    )
})
}
    

    
    /**
     * Adds, or replaces, the document stored under `id`.
     *
     * The host passes raw `text`; normalization runs inside the engine, so the
     * engine's profile is applied identically to indexed text and to queries.
     * Calling `index` again with an existing `id` overwrites that document.
     */
open func index(id: Int64, text: String)throws  {try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_method_searchengine_index(self.uniffiClonePointer(),
        FfiConverterInt64.lower(id),
        FfiConverterString.lower(text),$0
    )
}
}
    
    /**
     * Regenerates the index by re-normalizing every stored document's raw text
     * with this engine's current profile, then stamps that profile.
     *
     * Use this after changing the normalization profile (or its underlying
     * rules) to bring already-indexed documents back in sync without the host
     * re-feeding them. Documents indexed before raw text was retained have no
     * raw to normalize and are skipped. Returns the number of documents
     * regenerated.
     */
open func reindex()throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_method_searchengine_reindex(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Removes the document stored under `id`. A no-op if no such document
     * exists.
     */
open func remove(id: Int64)throws  {try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_method_searchengine_remove(self.uniffiClonePointer(),
        FfiConverterInt64.lower(id),$0
    )
}
}
    
    /**
     * Searches the index and returns at most `limit` hits.
     *
     * The `query` is normalized with the engine's profile and then matched
     * using the engine's strategy. A query that is empty — or only whitespace
     * once normalized — returns no hits. Ordering and scoring depend on the
     * strategy (see `Hit.score`).
     */
open func search(query: String, limit: UInt32)throws  -> [Hit] {
    return try  FfiConverterSequenceTypeHit.lift(try rustCallWithError(FfiConverterTypeSearchError.lift) {
    uniffi_unfydqry_fn_method_searchengine_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SearchEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SearchEngine {
        return SearchEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SearchEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SearchEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> SearchEngine {
    return try FfiConverterTypeSearchEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchEngine_lower(_ value: SearchEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSearchEngine.lower(value)
}


/**
 * The combination the host selects when constructing an engine.
 */
public struct EngineConfig {
    /**
     * How text is normalized at both index and query time.
     */
    public var normalize: NormalizeProfile
    /**
     * Which query algorithm `SearchEngine.search` uses.
     */
    public var strategy: SearchStrategy

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * How text is normalized at both index and query time.
         */normalize: NormalizeProfile, 
        /**
         * Which query algorithm `SearchEngine.search` uses.
         */strategy: SearchStrategy) {
        self.normalize = normalize
        self.strategy = strategy
    }
}



extension EngineConfig: Equatable, Hashable {
    public static func ==(lhs: EngineConfig, rhs: EngineConfig) -> Bool {
        if lhs.normalize != rhs.normalize {
            return false
        }
        if lhs.strategy != rhs.strategy {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(normalize)
        hasher.combine(strategy)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineConfig {
        return
            try EngineConfig(
                normalize: FfiConverterTypeNormalizeProfile.read(from: &buf), 
                strategy: FfiConverterTypeSearchStrategy.read(from: &buf)
        )
    }

    public static func write(_ value: EngineConfig, into buf: inout [UInt8]) {
        FfiConverterTypeNormalizeProfile.write(value.normalize, into: &buf)
        FfiConverterTypeSearchStrategy.write(value.strategy, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lift(_ buf: RustBuffer) throws -> EngineConfig {
    return try FfiConverterTypeEngineConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lower(_ value: EngineConfig) -> RustBuffer {
    return FfiConverterTypeEngineConfig.lower(value)
}


/**
 * Like [`EngineConfig`], but selects normalization with a composable
 * [`NormalizeOptions`] set instead of a named preset. Used by the
 * `withOptions` / `withOptionsRebuilding` constructors.
 */
public struct EngineOptionsConfig {
    /**
     * The composable normalization steps applied at index and query time.
     */
    public var normalize: NormalizeOptions
    /**
     * Which query algorithm `SearchEngine.search` uses.
     */
    public var strategy: SearchStrategy

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The composable normalization steps applied at index and query time.
         */normalize: NormalizeOptions, 
        /**
         * Which query algorithm `SearchEngine.search` uses.
         */strategy: SearchStrategy) {
        self.normalize = normalize
        self.strategy = strategy
    }
}



extension EngineOptionsConfig: Equatable, Hashable {
    public static func ==(lhs: EngineOptionsConfig, rhs: EngineOptionsConfig) -> Bool {
        if lhs.normalize != rhs.normalize {
            return false
        }
        if lhs.strategy != rhs.strategy {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(normalize)
        hasher.combine(strategy)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineOptionsConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineOptionsConfig {
        return
            try EngineOptionsConfig(
                normalize: FfiConverterTypeNormalizeOptions.read(from: &buf), 
                strategy: FfiConverterTypeSearchStrategy.read(from: &buf)
        )
    }

    public static func write(_ value: EngineOptionsConfig, into buf: inout [UInt8]) {
        FfiConverterTypeNormalizeOptions.write(value.normalize, into: &buf)
        FfiConverterTypeSearchStrategy.write(value.strategy, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineOptionsConfig_lift(_ buf: RustBuffer) throws -> EngineOptionsConfig {
    return try FfiConverterTypeEngineOptionsConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineOptionsConfig_lower(_ value: EngineOptionsConfig) -> RustBuffer {
    return FfiConverterTypeEngineOptionsConfig.lower(value)
}


/**
 * A single search result: the stable `id` the host indexed under, plus a
 * relevance `score`.
 *
 * The engine returns only ids and scores — never the document text — so the
 * host re-fetches the full record from its own source-of-truth store.
 */
public struct Hit {
    /**
     * The id the document was indexed under (see `index`).
     */
    public var id: Int64
    /**
     * Relevance score. For ranked strategies a smaller value is a better
     * match (bm25 for `trigramBm25`, `1 − similarity` for `fuzzyTrigram`,
     * edit distance for the Levenshtein strategies). Unranked strategies
     * (`substring`, `prefix`, `suffix`, `allTerms`) always report `0.0`.
     */
    public var score: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The id the document was indexed under (see `index`).
         */id: Int64, 
        /**
         * Relevance score. For ranked strategies a smaller value is a better
         * match (bm25 for `trigramBm25`, `1 − similarity` for `fuzzyTrigram`,
         * edit distance for the Levenshtein strategies). Unranked strategies
         * (`substring`, `prefix`, `suffix`, `allTerms`) always report `0.0`.
         */score: Double) {
        self.id = id
        self.score = score
    }
}



extension Hit: Equatable, Hashable {
    public static func ==(lhs: Hit, rhs: Hit) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(score)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Hit {
        return
            try Hit(
                id: FfiConverterInt64.read(from: &buf), 
                score: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Hit, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterDouble.write(value.score, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHit_lift(_ buf: RustBuffer) throws -> Hit {
    return try FfiConverterTypeHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHit_lower(_ value: Hit) -> RustBuffer {
    return FfiConverterTypeHit.lower(value)
}


/**
 * A composable set of normalization steps, all opt-in on top of the always-on
 * NFKC foundation. The engine applies the enabled steps in a fixed canonical
 * order (see `normalize/mod.rs`), so any combination is deterministic and
 * identical across platforms.
 */
public struct NormalizeOptions {
    /**
     * Fold case via `char::to_lowercase`.
     */
    public var lowercase: Bool
    /**
     * Map katakana to hiragana (カ → か); dakuten stays distinct.
     */
    public var kanaFold: Bool
    /**
     * Strip Latin/Western combining diacritics (café → cafe).
     */
    public var foldDiacritics: Bool
    /**
     * Fold the prolonged-sound mark after kana (サーバー → サーバ).
     */
    public var foldChoonpu: Bool
    /**
     * Expand iteration marks (時々 → 時時, こゞ → こご).
     */
    public var expandIterationMarks: Bool
    /**
     * Unify the dash/hyphen family to ASCII `-`.
     */
    public var normalizeHyphens: Bool
    /**
     * Remove digit-grouping commas (1,000 → 1000).
     */
    public var stripDigitGrouping: Bool
    /**
     * Collapse whitespace runs to a single space and trim.
     */
    public var collapseWhitespace: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Fold case via `char::to_lowercase`.
         */lowercase: Bool = false, 
        /**
         * Map katakana to hiragana (カ → か); dakuten stays distinct.
         */kanaFold: Bool = false, 
        /**
         * Strip Latin/Western combining diacritics (café → cafe).
         */foldDiacritics: Bool = false, 
        /**
         * Fold the prolonged-sound mark after kana (サーバー → サーバ).
         */foldChoonpu: Bool = false, 
        /**
         * Expand iteration marks (時々 → 時時, こゞ → こご).
         */expandIterationMarks: Bool = false, 
        /**
         * Unify the dash/hyphen family to ASCII `-`.
         */normalizeHyphens: Bool = false, 
        /**
         * Remove digit-grouping commas (1,000 → 1000).
         */stripDigitGrouping: Bool = false, 
        /**
         * Collapse whitespace runs to a single space and trim.
         */collapseWhitespace: Bool = false) {
        self.lowercase = lowercase
        self.kanaFold = kanaFold
        self.foldDiacritics = foldDiacritics
        self.foldChoonpu = foldChoonpu
        self.expandIterationMarks = expandIterationMarks
        self.normalizeHyphens = normalizeHyphens
        self.stripDigitGrouping = stripDigitGrouping
        self.collapseWhitespace = collapseWhitespace
    }
}



extension NormalizeOptions: Equatable, Hashable {
    public static func ==(lhs: NormalizeOptions, rhs: NormalizeOptions) -> Bool {
        if lhs.lowercase != rhs.lowercase {
            return false
        }
        if lhs.kanaFold != rhs.kanaFold {
            return false
        }
        if lhs.foldDiacritics != rhs.foldDiacritics {
            return false
        }
        if lhs.foldChoonpu != rhs.foldChoonpu {
            return false
        }
        if lhs.expandIterationMarks != rhs.expandIterationMarks {
            return false
        }
        if lhs.normalizeHyphens != rhs.normalizeHyphens {
            return false
        }
        if lhs.stripDigitGrouping != rhs.stripDigitGrouping {
            return false
        }
        if lhs.collapseWhitespace != rhs.collapseWhitespace {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(lowercase)
        hasher.combine(kanaFold)
        hasher.combine(foldDiacritics)
        hasher.combine(foldChoonpu)
        hasher.combine(expandIterationMarks)
        hasher.combine(normalizeHyphens)
        hasher.combine(stripDigitGrouping)
        hasher.combine(collapseWhitespace)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNormalizeOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NormalizeOptions {
        return
            try NormalizeOptions(
                lowercase: FfiConverterBool.read(from: &buf), 
                kanaFold: FfiConverterBool.read(from: &buf), 
                foldDiacritics: FfiConverterBool.read(from: &buf), 
                foldChoonpu: FfiConverterBool.read(from: &buf), 
                expandIterationMarks: FfiConverterBool.read(from: &buf), 
                normalizeHyphens: FfiConverterBool.read(from: &buf), 
                stripDigitGrouping: FfiConverterBool.read(from: &buf), 
                collapseWhitespace: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: NormalizeOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.lowercase, into: &buf)
        FfiConverterBool.write(value.kanaFold, into: &buf)
        FfiConverterBool.write(value.foldDiacritics, into: &buf)
        FfiConverterBool.write(value.foldChoonpu, into: &buf)
        FfiConverterBool.write(value.expandIterationMarks, into: &buf)
        FfiConverterBool.write(value.normalizeHyphens, into: &buf)
        FfiConverterBool.write(value.stripDigitGrouping, into: &buf)
        FfiConverterBool.write(value.collapseWhitespace, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeOptions_lift(_ buf: RustBuffer) throws -> NormalizeOptions {
    return try FfiConverterTypeNormalizeOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeOptions_lower(_ value: NormalizeOptions) -> RustBuffer {
    return FfiConverterTypeNormalizeOptions.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Which normalization pipeline runs at index and query time.
 *
 * `Loose` is the original behaviour (NFKC → katakana→hiragana → lowercase).
 */

public enum NormalizeProfile {
    
    /**
     * The original behaviour: NFKC, then katakana→hiragana, then lowercase,
     * so case, width, and kana variant all fold together.
     */
    case loose
    /**
     * NFKC + lowercase only; kana variants are kept distinct.
     */
    case nfkcCaseFold
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNormalizeProfile: FfiConverterRustBuffer {
    typealias SwiftType = NormalizeProfile

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NormalizeProfile {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .loose
        
        case 2: return .nfkcCaseFold
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NormalizeProfile, into buf: inout [UInt8]) {
        switch value {
        
        
        case .loose:
            writeInt(&buf, Int32(1))
        
        
        case .nfkcCaseFold:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeProfile_lift(_ buf: RustBuffer) throws -> NormalizeProfile {
    return try FfiConverterTypeNormalizeProfile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeProfile_lower(_ value: NormalizeProfile) -> RustBuffer {
    return FfiConverterTypeNormalizeProfile.lower(value)
}



extension NormalizeProfile: Equatable, Hashable {}




/**
 * An error surfaced across the FFI boundary by `SearchEngine`.
 */
public enum SearchError {

    
    
    /**
     * An underlying SQLite / storage failure; the associated string is its
     * message.
     */
    case Db(String
    )
    /**
     * The on-disk index was built with a different normalization profile
     * than the one requested. Indexed text is profile-specific, so the index
     * must be rebuilt to change profiles. `stored` is the profile recorded in
     * the index; `requested` is the one just asked for.
     */
    case ConfigMismatch(stored: String, requested: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchError: FfiConverterRustBuffer {
    typealias SwiftType = SearchError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Db(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .ConfigMismatch(
            stored: try FfiConverterString.read(from: &buf), 
            requested: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SearchError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Db(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConfigMismatch(stored,requested):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(stored, into: &buf)
            FfiConverterString.write(requested, into: &buf)
            
        }
    }
}


extension SearchError: Equatable, Hashable {}

extension SearchError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Which query algorithm `SearchEngine::search` uses.
 */

public enum SearchStrategy {
    
    /**
     * Trigram FTS5 + bm25, with a LIKE fallback for queries shorter than 3 chars.
     */
    case trigramBm25
    /**
     * Substring match (`LIKE '%q%'`) for every query.
     */
    case substring
    /**
     * Prefix match (`LIKE 'q%'`) for every query.
     */
    case prefix
    /**
     * Suffix match (`LIKE '%q'`) for every query.
     */
    case suffix
    /**
     * Every whitespace-separated term must appear (substring), order-independent.
     */
    case allTerms
    /**
     * Character-trigram set similarity (Jaccard); ranked by 1 − similarity.
     */
    case fuzzyTrigram
    /**
     * Typo-tolerant: min Levenshtein distance to any word in the doc.
     */
    case levenshtein
    /**
     * Like `Levenshtein`, but an adjacent transposition counts as one edit.
     */
    case damerauLevenshtein
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchStrategy: FfiConverterRustBuffer {
    typealias SwiftType = SearchStrategy

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchStrategy {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .trigramBm25
        
        case 2: return .substring
        
        case 3: return .prefix
        
        case 4: return .suffix
        
        case 5: return .allTerms
        
        case 6: return .fuzzyTrigram
        
        case 7: return .levenshtein
        
        case 8: return .damerauLevenshtein
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SearchStrategy, into buf: inout [UInt8]) {
        switch value {
        
        
        case .trigramBm25:
            writeInt(&buf, Int32(1))
        
        
        case .substring:
            writeInt(&buf, Int32(2))
        
        
        case .prefix:
            writeInt(&buf, Int32(3))
        
        
        case .suffix:
            writeInt(&buf, Int32(4))
        
        
        case .allTerms:
            writeInt(&buf, Int32(5))
        
        
        case .fuzzyTrigram:
            writeInt(&buf, Int32(6))
        
        
        case .levenshtein:
            writeInt(&buf, Int32(7))
        
        
        case .damerauLevenshtein:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchStrategy_lift(_ buf: RustBuffer) throws -> SearchStrategy {
    return try FfiConverterTypeSearchStrategy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchStrategy_lower(_ value: SearchStrategy) -> RustBuffer {
    return FfiConverterTypeSearchStrategy.lower(value)
}



extension SearchStrategy: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHit: FfiConverterRustBuffer {
    typealias SwiftType = [Hit]

    public static func write(_ value: [Hit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Hit] {
        let len: Int32 = try readInt(&buf)
        var seq = [Hit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHit.read(from: &buf))
        }
        return seq
    }
}
/**
 * Returns `input` normalized with the default `loose` profile (NFKC, then
 * katakana→hiragana, then lowercase).
 *
 * This is the same normalization the engine applies to indexed text and
 * queries by default; exposed so a host can preview or debug how a string
 * will be folded before searching.
 */
public func normalizeLoose(input: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_unfydqry_fn_func_normalizeloose(
        FfiConverterString.lower(input),$0
    )
})
}
/**
 * Normalizes `input` with a composable `NormalizeOptions` set — the same
 * transform the engine applies when opened via `withOptions`. Exposed so a
 * host can preview how a string folds under a given combination of steps.
 */
public func normalizeWithOptions(input: String, options: NormalizeOptions) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_unfydqry_fn_func_normalizewithoptions(
        FfiConverterString.lower(input),
        FfiConverterTypeNormalizeOptions.lower(options),$0
    )
})
}
/**
 * Like `normalizeLoose`, but lets the caller pick the normalization profile.
 */
public func normalizeWithProfile(input: String, profile: NormalizeProfile) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_unfydqry_fn_func_normalizewithprofile(
        FfiConverterString.lower(input),
        FfiConverterTypeNormalizeProfile.lower(profile),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_unfydqry_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_unfydqry_checksum_func_normalizeloose() != 36363) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_func_normalizewithoptions() != 33141) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_func_normalizewithprofile() != 49347) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_index() != 36421) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_reindex() != 31136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_remove() != 44114) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_search() != 59606) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_new() != 487) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withconfig() != 18262) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withconfigrebuilding() != 47325) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withoptions() != 4538) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withoptionsrebuilding() != 9643) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all