// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(unfydqryFFI)
import unfydqryFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_unfydqry_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_unfydqry_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureUnfydqryInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A persistent full-text search index backed by SQLite.
 *
 * Create one with `SearchEngine(dbPath:)` for the default behaviour, or
 * `SearchEngine.withConfig(dbPath:config:)` to choose a normalization profile
 * and a search strategy. Add or update documents with `index`, drop them with
 * `remove`, and query with `search`. The instance is safe to share across
 * threads.
 *
 * The engine stores both the raw host text and its normalized form, so the
 * index can be regenerated in place after a normalization change — explicitly
 * via `reindex`, or automatically by opening with
 * `SearchEngine.withConfigRebuilding(dbPath:config:)`.
 */
public protocol SearchEngineProtocol: AnyObject, Sendable {
    
    /**
     * Re-packs every stored id from the index's current `field_bits` to
     * `new_field_bits`, rebuilding the id encoding in place. Returns the
     * number of documents repacked.
     *
     * All-or-nothing: if any stored slot or record id would not fit under
     * `new_field_bits` (or a stored id is negative, i.e. not produced by the
     * record-layer API), the index is left untouched and an error is returned.
     */
    func changeFieldBits(newFieldBits: UInt8) throws  -> UInt64
    
    /**
     * Returns whether a document with the given `id` exists in the index.
     */
    func contains(id: Int64) throws  -> Bool
    
    /**
     * Returns whether any field of `record_id` exists in the index.
     *
     * This is the record-layer counterpart of `contains`: it checks whether
     * any packed id in the record's range `[lo, hi]` exists in the `entries`
     * table. Returns an error if `record_id` is out of range for the current
     * `field_bits`.
     */
    func containsRecord(recordId: Int64) throws  -> Bool
    
    /**
     * Returns the total number of documents in the index.
     */
    func documentCount() throws  -> UInt64
    
    /**
     * Returns the host's original text for the document at `id` with the
     * regions matching `query` wrapped in `before`/`after` markers.
     *
     * Returns `nil` / `null` if the document does not exist or if the
     * normalized query is empty.  When the document exists but the query does
     * not match, the original text is returned without markers.
     *
     * Matching happens on the *normalized* text (the same folding applied at
     * index and search time), but the marked regions are then mapped back onto
     * the raw text the host indexed, so the result preserves the original
     * casing, width, and kana rather than the folded form. Documents indexed
     * before raw text was retained have no raw to map onto; for those the
     * normalized text is marked directly.
     */
    func highlight(query: String, id: Int64, before: String, after: String) throws  -> String?
    
    /**
     * Adds, or replaces, the document stored under `id`.
     *
     * The host passes raw `text`; normalization runs inside the engine, so the
     * engine's profile is applied identically to indexed text and to queries.
     * Calling `index` again with an existing `id` overwrites that document.
     */
    func index(id: Int64, text: String) throws 
    
    /**
     * Adds, or replaces, the whole record `record_id`, made of multiple
     * fields.
     *
     * Each field is stored under a stable id that packs `(record_id, slot)`;
     * fields that are empty once normalized are dropped. Re-calling with an
     * existing `record_id` fully replaces its previous fields. `record_id`
     * must be in `0..=2^(63-field_bits) - 1` and every `slot` must be
     * `< 2^field_bits`, otherwise an error is returned and nothing is written.
     */
    func indexRecord(recordId: Int64, fields: [FieldValue]) throws 
    
    /**
     * Returns the total number of documents matching `query`, without a limit.
     *
     * This is useful for displaying "About N results" in search UIs. The
     * query is normalized the same way as `search`. Returns `0` for empty
     * or whitespace-only queries.
     */
    func matchCount(query: String) throws  -> UInt64
    
    /**
     * Regenerates the index by re-normalizing every stored document's raw text
     * with this engine's current profile, then stamps that profile.
     *
     * Use this after changing the normalization profile (or its underlying
     * rules) to bring already-indexed documents back in sync without the host
     * re-feeding them. Documents indexed before raw text was retained have no
     * raw to normalize and are skipped. Returns the number of documents
     * regenerated.
     */
    func reindex() throws  -> UInt64
    
    /**
     * Removes the document stored under `id`. A no-op if no such document
     * exists.
     */
    func remove(id: Int64) throws 
    
    /**
     * Removes all documents from the index. Returns the number of documents
     * removed.
     */
    func removeAll() throws  -> UInt64
    
    /**
     * Removes every field of `record_id`. A no-op if none exist.
     */
    func removeRecord(recordId: Int64) throws 
    
    /**
     * Searches the index and returns at most `limit` hits.
     *
     * The `query` is normalized with the engine's profile and then matched
     * using the engine's strategy. A query that is empty — or only whitespace
     * once normalized — returns no hits. Ordering and scoring depend on the
     * strategy (see `Hit.score`).
     */
    func search(query: String, limit: UInt32) throws  -> [Hit]
    
    /**
     * Returns up to `per_page` hits for the given `page` (0-indexed).
     *
     * Equivalent to `search` with an offset of `page * per_page`. Page 0 with
     * a given `per_page` returns the same results as `search(query, per_page)`.
     * Combine with `match_count` to compute the total number of pages.
     */
    func searchPage(query: String, perPage: UInt32, page: UInt32) throws  -> [Hit]
    
    /**
     * Searches across record fields and returns at most `limit` records,
     * ranked by their best matching field (smallest score first).
     *
     * `fields_per_record` is the host's field count, used only as an
     * over-fetch hint so that collapsing field hits back to records still
     * yields roughly `limit` records. An empty (or whitespace-only once
     * normalized) query returns no records.
     */
    func searchRecords(query: String, limit: UInt32, fieldsPerRecord: UInt32) throws  -> [RecordHit]
    
}
/**
 * A persistent full-text search index backed by SQLite.
 *
 * Create one with `SearchEngine(dbPath:)` for the default behaviour, or
 * `SearchEngine.withConfig(dbPath:config:)` to choose a normalization profile
 * and a search strategy. Add or update documents with `index`, drop them with
 * `remove`, and query with `search`. The instance is safe to share across
 * threads.
 *
 * The engine stores both the raw host text and its normalized form, so the
 * index can be regenerated in place after a normalization change — explicitly
 * via `reindex`, or automatically by opening with
 * `SearchEngine.withConfigRebuilding(dbPath:config:)`.
 */
open class SearchEngine: SearchEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_unfydqry_fn_clone_searchengine(self.handle, $0) }
    }
    /**
     * Opens the index with the default behaviour (loose normalization +
     * trigram/bm25). Kept for backward compatibility.
     */
public convenience init(dbPath: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_constructor_searchengine_new(
        FfiConverterString.lower(dbPath),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_unfydqry_fn_free_searchengine(handle, $0) }
    }

    
    /**
     * Opens the index with a host-selected combination of normalization
     * profile and search strategy.
     *
     * If the index already holds documents normalized under a *different*
     * profile, this returns `ConfigMismatch` rather than silently mixing
     * profiles. To regenerate the index under the new profile instead of
     * failing, open with `withConfigRebuilding`, or call `reindex` on an
     * engine opened with the matching profile.
     */
public static func withConfig(dbPath: String, config: EngineConfig)throws  -> SearchEngine  {
    return try  FfiConverterTypeSearchEngine_lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withconfig(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineConfig_lower(config),$0
    )
})
}
    
    /**
     * Opens the index under `config`, regenerating it in place when the stored
     * documents were normalized under a different profile.
     *
     * Unlike `withConfig`, a profile change is not an error here: the engine
     * re-normalizes every stored document from its retained raw text under the
     * new profile before returning. Documents indexed before raw text was
     * retained cannot be regenerated and are left untouched.
     */
public static func withConfigRebuilding(dbPath: String, config: EngineConfig)throws  -> SearchEngine  {
    return try  FfiConverterTypeSearchEngine_lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withconfigrebuilding(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineConfig_lower(config),$0
    )
})
}
    
    /**
     * Like `withConfig`, but selects normalization with a composable
     * `NormalizeOptions` set instead of a named preset. A fingerprint mismatch
     * with the stored index is a `ConfigMismatch`; use `withOptionsRebuilding`
     * to regenerate instead.
     */
public static func withOptions(dbPath: String, config: EngineOptionsConfig)throws  -> SearchEngine  {
    return try  FfiConverterTypeSearchEngine_lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withoptions(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineOptionsConfig_lower(config),$0
    )
})
}
    
    /**
     * Like `withConfigRebuilding`, but selects normalization with a composable
     * `NormalizeOptions` set. A change in the enabled steps regenerates the
     * index in place from the retained raw text.
     */
public static func withOptionsRebuilding(dbPath: String, config: EngineOptionsConfig)throws  -> SearchEngine  {
    return try  FfiConverterTypeSearchEngine_lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_constructor_searchengine_withoptionsrebuilding(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineOptionsConfig_lower(config),$0
    )
})
}
    

    
    /**
     * Re-packs every stored id from the index's current `field_bits` to
     * `new_field_bits`, rebuilding the id encoding in place. Returns the
     * number of documents repacked.
     *
     * All-or-nothing: if any stored slot or record id would not fit under
     * `new_field_bits` (or a stored id is negative, i.e. not produced by the
     * record-layer API), the index is left untouched and an error is returned.
     */
open func changeFieldBits(newFieldBits: UInt8)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_change_field_bits(
            self.uniffiCloneHandle(),
        FfiConverterUInt8.lower(newFieldBits),$0
    )
})
}
    
    /**
     * Returns whether a document with the given `id` exists in the index.
     */
open func contains(id: Int64)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_contains(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(id),$0
    )
})
}
    
    /**
     * Returns whether any field of `record_id` exists in the index.
     *
     * This is the record-layer counterpart of `contains`: it checks whether
     * any packed id in the record's range `[lo, hi]` exists in the `entries`
     * table. Returns an error if `record_id` is out of range for the current
     * `field_bits`.
     */
open func containsRecord(recordId: Int64)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_contains_record(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(recordId),$0
    )
})
}
    
    /**
     * Returns the total number of documents in the index.
     */
open func documentCount()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_document_count(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Returns the host's original text for the document at `id` with the
     * regions matching `query` wrapped in `before`/`after` markers.
     *
     * Returns `nil` / `null` if the document does not exist or if the
     * normalized query is empty.  When the document exists but the query does
     * not match, the original text is returned without markers.
     *
     * Matching happens on the *normalized* text (the same folding applied at
     * index and search time), but the marked regions are then mapped back onto
     * the raw text the host indexed, so the result preserves the original
     * casing, width, and kana rather than the folded form. Documents indexed
     * before raw text was retained have no raw to map onto; for those the
     * normalized text is marked directly.
     */
open func highlight(query: String, id: Int64, before: String, after: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_highlight(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterInt64.lower(id),
        FfiConverterString.lower(before),
        FfiConverterString.lower(after),$0
    )
})
}
    
    /**
     * Adds, or replaces, the document stored under `id`.
     *
     * The host passes raw `text`; normalization runs inside the engine, so the
     * engine's profile is applied identically to indexed text and to queries.
     * Calling `index` again with an existing `id` overwrites that document.
     */
open func index(id: Int64, text: String)throws   {try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_index(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(id),
        FfiConverterString.lower(text),$0
    )
}
}
    
    /**
     * Adds, or replaces, the whole record `record_id`, made of multiple
     * fields.
     *
     * Each field is stored under a stable id that packs `(record_id, slot)`;
     * fields that are empty once normalized are dropped. Re-calling with an
     * existing `record_id` fully replaces its previous fields. `record_id`
     * must be in `0..=2^(63-field_bits) - 1` and every `slot` must be
     * `< 2^field_bits`, otherwise an error is returned and nothing is written.
     */
open func indexRecord(recordId: Int64, fields: [FieldValue])throws   {try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_index_record(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(recordId),
        FfiConverterSequenceTypeFieldValue.lower(fields),$0
    )
}
}
    
    /**
     * Returns the total number of documents matching `query`, without a limit.
     *
     * This is useful for displaying "About N results" in search UIs. The
     * query is normalized the same way as `search`. Returns `0` for empty
     * or whitespace-only queries.
     */
open func matchCount(query: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_match_count(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Regenerates the index by re-normalizing every stored document's raw text
     * with this engine's current profile, then stamps that profile.
     *
     * Use this after changing the normalization profile (or its underlying
     * rules) to bring already-indexed documents back in sync without the host
     * re-feeding them. Documents indexed before raw text was retained have no
     * raw to normalize and are skipped. Returns the number of documents
     * regenerated.
     */
open func reindex()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_reindex(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Removes the document stored under `id`. A no-op if no such document
     * exists.
     */
open func remove(id: Int64)throws   {try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_remove(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(id),$0
    )
}
}
    
    /**
     * Removes all documents from the index. Returns the number of documents
     * removed.
     */
open func removeAll()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_remove_all(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Removes every field of `record_id`. A no-op if none exist.
     */
open func removeRecord(recordId: Int64)throws   {try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_remove_record(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(recordId),$0
    )
}
}
    
    /**
     * Searches the index and returns at most `limit` hits.
     *
     * The `query` is normalized with the engine's profile and then matched
     * using the engine's strategy. A query that is empty — or only whitespace
     * once normalized — returns no hits. Ordering and scoring depend on the
     * strategy (see `Hit.score`).
     */
open func search(query: String, limit: UInt32)throws  -> [Hit]  {
    return try  FfiConverterSequenceTypeHit.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_search(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
    /**
     * Returns up to `per_page` hits for the given `page` (0-indexed).
     *
     * Equivalent to `search` with an offset of `page * per_page`. Page 0 with
     * a given `per_page` returns the same results as `search(query, per_page)`.
     * Combine with `match_count` to compute the total number of pages.
     */
open func searchPage(query: String, perPage: UInt32, page: UInt32)throws  -> [Hit]  {
    return try  FfiConverterSequenceTypeHit.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_search_page(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(perPage),
        FfiConverterUInt32.lower(page),$0
    )
})
}
    
    /**
     * Searches across record fields and returns at most `limit` records,
     * ranked by their best matching field (smallest score first).
     *
     * `fields_per_record` is the host's field count, used only as an
     * over-fetch hint so that collapsing field hits back to records still
     * yields roughly `limit` records. An empty (or whitespace-only once
     * normalized) query returns no records.
     */
open func searchRecords(query: String, limit: UInt32, fieldsPerRecord: UInt32)throws  -> [RecordHit]  {
    return try  FfiConverterSequenceTypeRecordHit.lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_method_searchengine_search_records(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(limit),
        FfiConverterUInt32.lower(fieldsPerRecord),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SearchEngine

    public static func lift(_ handle: UInt64) throws -> SearchEngine {
        return SearchEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SearchEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SearchEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchEngine_lift(_ handle: UInt64) throws -> SearchEngine {
    return try FfiConverterTypeSearchEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchEngine_lower(_ value: SearchEngine) -> UInt64 {
    return FfiConverterTypeSearchEngine.lower(value)
}




/**
 * The combination the host selects when constructing an engine.
 */
public struct EngineConfig: Equatable, Hashable {
    /**
     * How text is normalized at both index and query time.
     */
    public var normalize: NormalizeProfile
    /**
     * Which query algorithm `SearchEngine.search` uses.
     */
    public var strategy: SearchStrategy
    /**
     * Low bits of each packed id reserved for the field slot in the
     * record-layer API (`index_record` / `search_records`).
     *
     * `None` adopts the value the index was created with (or
     * [`DEFAULT_FIELD_BITS`] for a fresh index) and never errors on
     * field-bits — this keeps the "open without specifying field_bits"
     * interface working. `Some(n)` requires `n` (which must be in `1..=62`) and
     * rejects an index stamped with a different value
     * (`SearchError::FieldBitsMismatch`). Irrelevant to the plain
     * `index` / `search` API.
     */
    public var fieldBits: UInt8?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * How text is normalized at both index and query time.
         */normalize: NormalizeProfile, 
        /**
         * Which query algorithm `SearchEngine.search` uses.
         */strategy: SearchStrategy, 
        /**
         * Low bits of each packed id reserved for the field slot in the
         * record-layer API (`index_record` / `search_records`).
         *
         * `None` adopts the value the index was created with (or
         * [`DEFAULT_FIELD_BITS`] for a fresh index) and never errors on
         * field-bits — this keeps the "open without specifying field_bits"
         * interface working. `Some(n)` requires `n` (which must be in `1..=62`) and
         * rejects an index stamped with a different value
         * (`SearchError::FieldBitsMismatch`). Irrelevant to the plain
         * `index` / `search` API.
         */fieldBits: UInt8? = nil) {
        self.normalize = normalize
        self.strategy = strategy
        self.fieldBits = fieldBits
    }

    

    
}

#if compiler(>=6)
extension EngineConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineConfig {
        return
            try EngineConfig(
                normalize: FfiConverterTypeNormalizeProfile.read(from: &buf), 
                strategy: FfiConverterTypeSearchStrategy.read(from: &buf), 
                fieldBits: FfiConverterOptionUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: EngineConfig, into buf: inout [UInt8]) {
        FfiConverterTypeNormalizeProfile.write(value.normalize, into: &buf)
        FfiConverterTypeSearchStrategy.write(value.strategy, into: &buf)
        FfiConverterOptionUInt8.write(value.fieldBits, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lift(_ buf: RustBuffer) throws -> EngineConfig {
    return try FfiConverterTypeEngineConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lower(_ value: EngineConfig) -> RustBuffer {
    return FfiConverterTypeEngineConfig.lower(value)
}


/**
 * Like [`EngineConfig`], but selects normalization with a composable
 * [`NormalizeOptions`] set instead of a named preset. Used by the
 * `withOptions` / `withOptionsRebuilding` constructors.
 */
public struct EngineOptionsConfig: Equatable, Hashable {
    /**
     * The composable normalization steps applied at index and query time.
     */
    public var normalize: NormalizeOptions
    /**
     * Which query algorithm `SearchEngine.search` uses.
     */
    public var strategy: SearchStrategy
    /**
     * See [`EngineConfig::field_bits`]. `None` adopts the stored value.
     */
    public var fieldBits: UInt8?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The composable normalization steps applied at index and query time.
         */normalize: NormalizeOptions, 
        /**
         * Which query algorithm `SearchEngine.search` uses.
         */strategy: SearchStrategy, 
        /**
         * See [`EngineConfig::field_bits`]. `None` adopts the stored value.
         */fieldBits: UInt8? = nil) {
        self.normalize = normalize
        self.strategy = strategy
        self.fieldBits = fieldBits
    }

    

    
}

#if compiler(>=6)
extension EngineOptionsConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineOptionsConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineOptionsConfig {
        return
            try EngineOptionsConfig(
                normalize: FfiConverterTypeNormalizeOptions.read(from: &buf), 
                strategy: FfiConverterTypeSearchStrategy.read(from: &buf), 
                fieldBits: FfiConverterOptionUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: EngineOptionsConfig, into buf: inout [UInt8]) {
        FfiConverterTypeNormalizeOptions.write(value.normalize, into: &buf)
        FfiConverterTypeSearchStrategy.write(value.strategy, into: &buf)
        FfiConverterOptionUInt8.write(value.fieldBits, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineOptionsConfig_lift(_ buf: RustBuffer) throws -> EngineOptionsConfig {
    return try FfiConverterTypeEngineOptionsConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineOptionsConfig_lower(_ value: EngineOptionsConfig) -> RustBuffer {
    return FfiConverterTypeEngineOptionsConfig.lower(value)
}


/**
 * A single field of a host record, for the record-layer indexing API
 * (`index_record`).
 *
 * `slot` is a small, stable per-field number (0-based) chosen by the host. The
 * engine packs `(record_id, slot)` into the stable id it stores under, so a
 * slot, once used, must not be renumbered, and must be less than
 * `2^field_bits`.
 */
public struct FieldValue: Equatable, Hashable {
    /**
     * Stable per-field slot. Must be `< 2^field_bits`.
     */
    public var slot: UInt8
    /**
     * Raw field text; the engine normalizes it the same way as `index`.
     */
    public var text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stable per-field slot. Must be `< 2^field_bits`.
         */slot: UInt8, 
        /**
         * Raw field text; the engine normalizes it the same way as `index`.
         */text: String) {
        self.slot = slot
        self.text = text
    }

    

    
}

#if compiler(>=6)
extension FieldValue: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFieldValue: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FieldValue {
        return
            try FieldValue(
                slot: FfiConverterUInt8.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FieldValue, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.slot, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldValue_lift(_ buf: RustBuffer) throws -> FieldValue {
    return try FfiConverterTypeFieldValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldValue_lower(_ value: FieldValue) -> RustBuffer {
    return FfiConverterTypeFieldValue.lower(value)
}


/**
 * A single search result: the stable `id` the host indexed under, plus a
 * relevance `score`.
 *
 * The engine returns only ids and scores — never the document text — so the
 * host re-fetches the full record from its own source-of-truth store.
 */
public struct Hit: Equatable, Hashable {
    /**
     * The id the document was indexed under (see `index`).
     */
    public var id: Int64
    /**
     * Relevance score. For ranked strategies a smaller value is a better
     * match (bm25 for `trigramBm25`, `1 − similarity` for `fuzzyTrigram`,
     * edit distance for the Levenshtein strategies). Unranked strategies
     * (`substring`, `prefix`, `suffix`, `allTerms`) always report `0.0`.
     */
    public var score: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The id the document was indexed under (see `index`).
         */id: Int64, 
        /**
         * Relevance score. For ranked strategies a smaller value is a better
         * match (bm25 for `trigramBm25`, `1 − similarity` for `fuzzyTrigram`,
         * edit distance for the Levenshtein strategies). Unranked strategies
         * (`substring`, `prefix`, `suffix`, `allTerms`) always report `0.0`.
         */score: Double) {
        self.id = id
        self.score = score
    }

    

    
}

#if compiler(>=6)
extension Hit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Hit {
        return
            try Hit(
                id: FfiConverterInt64.read(from: &buf), 
                score: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Hit, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterDouble.write(value.score, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHit_lift(_ buf: RustBuffer) throws -> Hit {
    return try FfiConverterTypeHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHit_lower(_ value: Hit) -> RustBuffer {
    return FfiConverterTypeHit.lower(value)
}


/**
 * A composable set of normalization steps, all opt-in on top of NFKC.
 *
 * The engine applies the enabled steps in a fixed canonical order (see
 * `normalize/mod.rs`), so any combination is deterministic and identical
 * across platforms.
 */
public struct NormalizeOptions: Equatable, Hashable {
    /**
     * Fold case via `char::to_lowercase`.
     */
    public var lowercase: Bool
    /**
     * Map katakana to hiragana (カ → か); dakuten stays distinct.
     */
    public var kanaFold: Bool
    /**
     * Strip Latin/Western combining diacritics (café → cafe).
     */
    public var foldDiacritics: Bool
    /**
     * Fold the prolonged-sound mark after kana (サーバー → サーバ).
     */
    public var foldChoonpu: Bool
    /**
     * Expand iteration marks (時々 → 時時, こゞ → こご).
     */
    public var expandIterationMarks: Bool
    /**
     * Unify the dash/hyphen family to ASCII `-`.
     */
    public var normalizeHyphens: Bool
    /**
     * Remove digit-grouping commas (1,000 → 1000).
     */
    public var stripDigitGrouping: Bool
    /**
     * Collapse whitespace runs to a single space and trim.
     */
    public var collapseWhitespace: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Fold case via `char::to_lowercase`.
         */lowercase: Bool = false, 
        /**
         * Map katakana to hiragana (カ → か); dakuten stays distinct.
         */kanaFold: Bool = false, 
        /**
         * Strip Latin/Western combining diacritics (café → cafe).
         */foldDiacritics: Bool = false, 
        /**
         * Fold the prolonged-sound mark after kana (サーバー → サーバ).
         */foldChoonpu: Bool = false, 
        /**
         * Expand iteration marks (時々 → 時時, こゞ → こご).
         */expandIterationMarks: Bool = false, 
        /**
         * Unify the dash/hyphen family to ASCII `-`.
         */normalizeHyphens: Bool = false, 
        /**
         * Remove digit-grouping commas (1,000 → 1000).
         */stripDigitGrouping: Bool = false, 
        /**
         * Collapse whitespace runs to a single space and trim.
         */collapseWhitespace: Bool = false) {
        self.lowercase = lowercase
        self.kanaFold = kanaFold
        self.foldDiacritics = foldDiacritics
        self.foldChoonpu = foldChoonpu
        self.expandIterationMarks = expandIterationMarks
        self.normalizeHyphens = normalizeHyphens
        self.stripDigitGrouping = stripDigitGrouping
        self.collapseWhitespace = collapseWhitespace
    }

    

    
}

#if compiler(>=6)
extension NormalizeOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNormalizeOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NormalizeOptions {
        return
            try NormalizeOptions(
                lowercase: FfiConverterBool.read(from: &buf), 
                kanaFold: FfiConverterBool.read(from: &buf), 
                foldDiacritics: FfiConverterBool.read(from: &buf), 
                foldChoonpu: FfiConverterBool.read(from: &buf), 
                expandIterationMarks: FfiConverterBool.read(from: &buf), 
                normalizeHyphens: FfiConverterBool.read(from: &buf), 
                stripDigitGrouping: FfiConverterBool.read(from: &buf), 
                collapseWhitespace: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: NormalizeOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.lowercase, into: &buf)
        FfiConverterBool.write(value.kanaFold, into: &buf)
        FfiConverterBool.write(value.foldDiacritics, into: &buf)
        FfiConverterBool.write(value.foldChoonpu, into: &buf)
        FfiConverterBool.write(value.expandIterationMarks, into: &buf)
        FfiConverterBool.write(value.normalizeHyphens, into: &buf)
        FfiConverterBool.write(value.stripDigitGrouping, into: &buf)
        FfiConverterBool.write(value.collapseWhitespace, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeOptions_lift(_ buf: RustBuffer) throws -> NormalizeOptions {
    return try FfiConverterTypeNormalizeOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeOptions_lower(_ value: NormalizeOptions) -> RustBuffer {
    return FfiConverterTypeNormalizeOptions.lower(value)
}


/**
 * A record-level search result from `search_records`: the host's `record_id`,
 * the best (smallest) score across its matching fields, and which field slots
 * matched.
 *
 * As with `Hit`, the engine returns only ids and scores; the host re-fetches
 * the full record from its own store.
 */
public struct RecordHit: Equatable, Hashable {
    /**
     * The host record id the matching fields belong to.
     */
    public var recordId: Int64
    /**
     * Best (smallest) score among the record's matching fields. See `Hit.score`.
     */
    public var score: Double
    /**
     * Slots of the fields that matched, ordered best (smallest score) first.
     */
    public var matchedSlots: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The host record id the matching fields belong to.
         */recordId: Int64, 
        /**
         * Best (smallest) score among the record's matching fields. See `Hit.score`.
         */score: Double, 
        /**
         * Slots of the fields that matched, ordered best (smallest score) first.
         */matchedSlots: Data) {
        self.recordId = recordId
        self.score = score
        self.matchedSlots = matchedSlots
    }

    

    
}

#if compiler(>=6)
extension RecordHit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecordHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecordHit {
        return
            try RecordHit(
                recordId: FfiConverterInt64.read(from: &buf), 
                score: FfiConverterDouble.read(from: &buf), 
                matchedSlots: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: RecordHit, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.recordId, into: &buf)
        FfiConverterDouble.write(value.score, into: &buf)
        FfiConverterData.write(value.matchedSlots, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordHit_lift(_ buf: RustBuffer) throws -> RecordHit {
    return try FfiConverterTypeRecordHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordHit_lower(_ value: RecordHit) -> RustBuffer {
    return FfiConverterTypeRecordHit.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Which normalization pipeline runs at index and query time.
 *
 * `Loose` is the original behaviour (NFKC → katakana→hiragana → lowercase).
 */

public enum NormalizeProfile: Equatable, Hashable {
    
    /**
     * The original behaviour: NFKC, then katakana→hiragana, then lowercase,
     * so case, width, and kana variant all fold together.
     */
    case loose
    /**
     * NFKC + lowercase only; kana variants are kept distinct.
     */
    case nfkcCaseFold





}

#if compiler(>=6)
extension NormalizeProfile: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNormalizeProfile: FfiConverterRustBuffer {
    typealias SwiftType = NormalizeProfile

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NormalizeProfile {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .loose
        
        case 2: return .nfkcCaseFold
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NormalizeProfile, into buf: inout [UInt8]) {
        switch value {
        
        
        case .loose:
            writeInt(&buf, Int32(1))
        
        
        case .nfkcCaseFold:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeProfile_lift(_ buf: RustBuffer) throws -> NormalizeProfile {
    return try FfiConverterTypeNormalizeProfile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNormalizeProfile_lower(_ value: NormalizeProfile) -> RustBuffer {
    return FfiConverterTypeNormalizeProfile.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Whether an on-disk index can be queried with a given normalization, or needs
 * regenerating first. Returned by `reindexStatus` / `reindexStatusWithOptions`.
 */

public enum ReindexStatus: Equatable, Hashable {
    
    /**
     * The index holds no documents; any normalization can be adopted freely
     * (no regeneration needed — the next `index` call stamps the profile).
     */
    case empty
    /**
     * The stored documents were already normalized with the requested
     * profile/options. The index is ready to query as-is.
     */
    case upToDate
    /**
     * The stored documents were normalized under a *different* profile/options.
     * Querying as-is would return wrong results — regenerate (via `reindex`,
     * `withConfigRebuilding`, or `withOptionsRebuilding`) before use.
     */
    case configChanged





}

#if compiler(>=6)
extension ReindexStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReindexStatus: FfiConverterRustBuffer {
    typealias SwiftType = ReindexStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReindexStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .empty
        
        case 2: return .upToDate
        
        case 3: return .configChanged
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ReindexStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .empty:
            writeInt(&buf, Int32(1))
        
        
        case .upToDate:
            writeInt(&buf, Int32(2))
        
        
        case .configChanged:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReindexStatus_lift(_ buf: RustBuffer) throws -> ReindexStatus {
    return try FfiConverterTypeReindexStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReindexStatus_lower(_ value: ReindexStatus) -> RustBuffer {
    return FfiConverterTypeReindexStatus.lower(value)
}



/**
 * An error surfaced across the FFI boundary by `SearchEngine`.
 */
public enum SearchError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * An underlying SQLite / storage failure; the associated string is its
     * message.
     */
    case Db(String
    )
    /**
     * The on-disk index was built with a different normalization profile
     * than the one requested. Indexed text is profile-specific, so the index
     * must be rebuilt to change profiles. `stored` is the profile recorded in
     * the index; `requested` is the one just asked for.
     */
    case ConfigMismatch(stored: String, requested: String
    )
    /**
     * The index was created with a different `field_bits` than requested. The
     * id packing is encoding-specific and fixed at creation, so this is not
     * auto-rebuilt: open with `field_bits: None` to adopt the stored value, or
     * call `change_field_bits` to re-pack the index. `stored` is the value
     * recorded in the index; `requested` is the one just asked for.
     */
    case FieldBitsMismatch(stored: UInt8, requested: UInt8
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SearchError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchError: FfiConverterRustBuffer {
    typealias SwiftType = SearchError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Db(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .ConfigMismatch(
            stored: try FfiConverterString.read(from: &buf), 
            requested: try FfiConverterString.read(from: &buf)
            )
        case 3: return .FieldBitsMismatch(
            stored: try FfiConverterUInt8.read(from: &buf), 
            requested: try FfiConverterUInt8.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SearchError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Db(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConfigMismatch(stored,requested):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(stored, into: &buf)
            FfiConverterString.write(requested, into: &buf)
            
        
        case let .FieldBitsMismatch(stored,requested):
            writeInt(&buf, Int32(3))
            FfiConverterUInt8.write(stored, into: &buf)
            FfiConverterUInt8.write(requested, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchError_lift(_ buf: RustBuffer) throws -> SearchError {
    return try FfiConverterTypeSearchError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchError_lower(_ value: SearchError) -> RustBuffer {
    return FfiConverterTypeSearchError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Which query algorithm `SearchEngine::search` uses.
 */

public enum SearchStrategy: Equatable, Hashable {
    
    /**
     * Trigram FTS5 + bm25, with a LIKE fallback for queries shorter than 3 chars.
     */
    case trigramBm25
    /**
     * Substring match (`LIKE '%q%'`) for every query.
     */
    case substring
    /**
     * Prefix match (`LIKE 'q%'`) for every query.
     */
    case prefix
    /**
     * Suffix match (`LIKE '%q'`) for every query.
     */
    case suffix
    /**
     * Every whitespace-separated term must appear (substring), order-independent.
     */
    case allTerms
    /**
     * Character-trigram set similarity (Jaccard); ranked by 1 − similarity.
     */
    case fuzzyTrigram
    /**
     * Typo-tolerant: min Levenshtein distance to any word in the doc.
     */
    case levenshtein
    /**
     * Like `Levenshtein`, but an adjacent transposition counts as one edit.
     */
    case damerauLevenshtein





}

#if compiler(>=6)
extension SearchStrategy: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchStrategy: FfiConverterRustBuffer {
    typealias SwiftType = SearchStrategy

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchStrategy {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .trigramBm25
        
        case 2: return .substring
        
        case 3: return .prefix
        
        case 4: return .suffix
        
        case 5: return .allTerms
        
        case 6: return .fuzzyTrigram
        
        case 7: return .levenshtein
        
        case 8: return .damerauLevenshtein
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SearchStrategy, into buf: inout [UInt8]) {
        switch value {
        
        
        case .trigramBm25:
            writeInt(&buf, Int32(1))
        
        
        case .substring:
            writeInt(&buf, Int32(2))
        
        
        case .prefix:
            writeInt(&buf, Int32(3))
        
        
        case .suffix:
            writeInt(&buf, Int32(4))
        
        
        case .allTerms:
            writeInt(&buf, Int32(5))
        
        
        case .fuzzyTrigram:
            writeInt(&buf, Int32(6))
        
        
        case .levenshtein:
            writeInt(&buf, Int32(7))
        
        
        case .damerauLevenshtein:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchStrategy_lift(_ buf: RustBuffer) throws -> SearchStrategy {
    return try FfiConverterTypeSearchStrategy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchStrategy_lower(_ value: SearchStrategy) -> RustBuffer {
    return FfiConverterTypeSearchStrategy.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFieldValue: FfiConverterRustBuffer {
    typealias SwiftType = [FieldValue]

    public static func write(_ value: [FieldValue], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFieldValue.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FieldValue] {
        let len: Int32 = try readInt(&buf)
        var seq = [FieldValue]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFieldValue.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHit: FfiConverterRustBuffer {
    typealias SwiftType = [Hit]

    public static func write(_ value: [Hit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Hit] {
        let len: Int32 = try readInt(&buf)
        var seq = [Hit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRecordHit: FfiConverterRustBuffer {
    typealias SwiftType = [RecordHit]

    public static func write(_ value: [RecordHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRecordHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RecordHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [RecordHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRecordHit.read(from: &buf))
        }
        return seq
    }
}
/**
 * Returns `input` normalized with the default `loose` profile (NFKC, then
 * katakana→hiragana, then lowercase).
 *
 * This is the same normalization the engine applies to indexed text and
 * queries by default; exposed so a host can preview or debug how a string
 * will be folded before searching.
 */
public func normalizeLoose(input: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_unfydqry_fn_func_normalizeloose(
        FfiConverterString.lower(input),$0
    )
})
}
/**
 * Normalizes `input` with a composable `NormalizeOptions` set — the same
 * transform the engine applies when opened via `withOptions`. Exposed so a
 * host can preview how a string folds under a given combination of steps.
 */
public func normalizeWithOptions(input: String, options: NormalizeOptions) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_unfydqry_fn_func_normalizewithoptions(
        FfiConverterString.lower(input),
        FfiConverterTypeNormalizeOptions_lower(options),$0
    )
})
}
/**
 * Like `normalizeLoose`, but lets the caller pick the normalization profile.
 */
public func normalizeWithProfile(input: String, profile: NormalizeProfile) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_unfydqry_fn_func_normalizewithprofile(
        FfiConverterString.lower(input),
        FfiConverterTypeNormalizeProfile_lower(profile),$0
    )
})
}
/**
 * Whether the index at `db_path` needs regenerating to be used with `config`'s
 * normalization profile. Lets a host decide between `withConfig` (when
 * `UpToDate`/`Empty`) and `withConfigRebuilding` / `reindex` (when
 * `ConfigChanged`) without first triggering a `ConfigMismatch` error.
 */
public func reindexStatus(dbPath: String, config: EngineConfig)throws  -> ReindexStatus  {
    return try  FfiConverterTypeReindexStatus_lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_func_reindexstatus(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeEngineConfig_lower(config),$0
    )
})
}
/**
 * Like `reindexStatus`, but for a composable `NormalizeOptions` set.
 */
public func reindexStatusWithOptions(dbPath: String, options: NormalizeOptions)throws  -> ReindexStatus  {
    return try  FfiConverterTypeReindexStatus_lift(try rustCallWithError(FfiConverterTypeSearchError_lift) {
    uniffi_unfydqry_fn_func_reindexstatuswithoptions(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeNormalizeOptions_lower(options),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_unfydqry_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_unfydqry_checksum_func_normalizeloose() != 36363) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_func_normalizewithoptions() != 41192) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_func_normalizewithprofile() != 24929) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_func_reindexstatus() != 2442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_func_reindexstatuswithoptions() != 37208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_change_field_bits() != 28105) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_contains() != 16638) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_contains_record() != 13256) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_document_count() != 24388) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_highlight() != 44743) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_index() != 46744) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_index_record() != 36062) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_match_count() != 11745) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_reindex() != 24527) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_remove() != 29881) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_remove_all() != 61569) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_remove_record() != 28442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_search() != 13991) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_search_page() != 60065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_method_searchengine_search_records() != 63653) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_new() != 23373) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withconfig() != 45331) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withconfigrebuilding() != 16805) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withoptions() != 2915) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_unfydqry_checksum_constructor_searchengine_withoptionsrebuilding() != 59715) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureUnfydqryInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all